# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
gems: [jekyll-seo-tag, jekyll-sitemap, jekyll-paginate]
paginate: 6

stageurl: "http://localhost:8000/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github:username:  evr01
social:
    name: Evan Rosa
    type: website
    telephone: 571-762-1956
    email: "erosa26@gmail.com"
    links:
        - https://www.facebook.com/erosa26/
        - https://github.com/evr01



# Build settings
markdown: kramdown

# Assets are being handled by Gulp
exclude: [assets]
keep_files: [assets]





collections:
    topic-web-design:
        output: true
        permalink: /blog/topic-digital-marketing/:path/
    topic-web-analytics:
        output: true
        permalink: /blog/topic-web-analytics/:path/
    topic-web-development:
        output: true
        permalink: /blog/topic-web-development/:path/
    topic-all:
        output: true
        permalink: /blog/topic-all/:path/




